openapi: 3.0.0
info:
  description: >
    The Credential Management REST API provides a comprehensive interface to list and delete end-user enrolled 
    credentials within the WSO2 Identity Server.
  version: '1.0'
  title: WSO2 Identity Server - Credential Management Rest API
  termsOfService: http://swagger.io/terms/
  contact:
    name: WSO2
    url: http://wso2.com/identity-server/
    email: architecture@wso2.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

security:
  - OAuth2: []
  - BasicAuth: []

servers:
  - url: https://{server-url}/t/{tenant-domain}/api/server/v1
    variables:
      tenant-domain:
        default: carbon.super
      server-url:
        default: localhost:9443

paths:
  /users/{user-id}/credentials:
    get:
      summary: Get all credentials for a user
      description: Retrieves a list of all user-enrolled credentials. Requires administrative privileges with appropriate scope and organizational permissions.
      tags:
        - Credential Management
      parameters:
        - name: user-id
          in: path
          description: The unique identifier of the user.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful retrieval of user authenticators. The list may be empty if the user has no enrolled credentials.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Credential'
        '400':
          description: Bad Request. The request is malformed, for example, due to an invalid user-id format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized. The request has not been applied because it lacks valid authentication credentials for the target resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden. The server understood the request but refuses to authorize it. This can happen if the administrator lacks the required permissions or is trying to access a user outside of their organizational hierarchy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found. The user specified by the user-id does not exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. An unexpected condition was encountered on the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/{user-id}/credentials/{type}/{credential-id}:
    delete:
      summary: Delete a user-enrolled credential.
      description: Deletes a specific enrolled credential for a user. Requires administrative privileges with appropriate scope and organizational permissions.
      tags:
        - Credential Management
      parameters:
        - name: user-id
          in: path
          description: The unique identifier of the user.
          required: true
          schema:
            type: string
        - name: type
          in: path
          description: The type of the credential.
          required: true
          schema:
            type: string
            enum: [passkey, push-auth]
        - name: credential-id
          in: path
          description: The unique identifier of the device to be deleted.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content. The device was successfully deleted.
        '400':
          description: Bad Request. The request is malformed, for example, due to an invalid user-id or device-id format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized. The request has not been applied because it lacks valid authentication credentials for the target resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden. The server understood the request but refuses to authorize it. This can happen if the administrator lacks the required permissions or is trying to access a user outside of their organizational hierarchy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found. The user specified by the user-id or the device specified by the device-id does not exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error. An unexpected condition was encountered on the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Credential:
      type: object
      properties:
        credentialId:
          type: string
          description: The unique identifier for the credential.
          example: 'a5a81c76-27a3-42d4-82a8-55285d82a4a1'
        displayName:
          type: string
          description: A user-friendly name for the credential (e.g., "John's iPhone" or "YubiKey 5").
          example: "YubiKey 5C"
        type:
          type: string
          description: The type of the credential.
          enum: [passkey, push-auth]
        registeredAt:
          type: string
          format: date-time
          description: The timestamp when the credential was registered.
          example: '2023-10-27T10:00:00Z'
    Error:
      type: object
      properties:
        code:
          type: string
          description: A unique, machine-readable error code following the WSO2 standard.
          example: 'CM-60401'
        message:
          type: string
          description: A human-readable summary of the error.
          example: 'User not found.'
        description:
          type: string
          description: A more detailed explanation of the error.
          example: 'The user specified by the user-id does not exist in the system.'
