openapi: 3.0.0
info:
  description: >
    This document specifies a **Debug RESTful API** for **WSO2 Identity Server**.
    This API supports debugging of various authentication flows and resource configurations.
    The APIs provide the capability to start and retrieve debug sessions for different resource types.
  version: "v1"
  title: WSO2 Identity Server - Debug API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: WSO2
    url: 'http://wso2.com/products/identity-server/'
    email: architecture@wso2.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: "/t/{tenant-domain}/api/server/v1"
    variables:
      tenant-domain:
        default: "carbon.super"
        description: "The tenant domain."

paths:
  /debug:
    post:
      summary: "Start Debug Session"
      description: "Initiates a debug session for any resource type (IDP, Application, etc.) with configurable properties."
      operationId: "startDebugSession"
      tags:
        - "Debug"
      requestBody:
        description: "Debug request with resource ID, resource type, and properties."
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DebugConnectionRequest"
      responses:
        '200':
          description: "Debug session initiated successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebugConnectionResponse"
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: "Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /debug/result/{session-id}:
    get:
      summary: "Get Debug Result"
      description: "Retrieves the debug results for a specific session ID."
      operationId: "getDebugResult"
      tags:
        - "Debug"
      parameters:
        - name: "session-id"
          in: "path"
          description: "The unique session ID for the debug flow."
          required: true
          schema:
            type: "string"
      responses:
        '200':
          description: "Debug result retrieved successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebugResponse"
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: "Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    # -------------
    # Common Error
    # -------------
    Error:
      type: "object"
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "IDP-60001"
          description: "An error code."
        message:
          type: string
          example: "Error message."
          description: "An error message."
        description:
          type: string
          example: "Detailed error description."
          description: "A detailed error description."
        traceId:
          type: string
          example: "trace-123456"
          description: "Trace identifier for error correlation."

    # ---------------------------------
    # Debug Request/Response Models
    # ---------------------------------
    DebugConnectionRequest:
      type: object
      required:
        - resourceType
      description: "Request body for starting a debug session. The connectionId is optional at the top level and can be provided inside the properties map for resource types that require it (e.g., IDP)."
      properties:
        resourceType:
          type: string
          minLength: 1
          maxLength: 50
          description: "Type of resource to debug. Allowed values: IDP, APPLICATION, CONNECTOR, AUTHENTICATOR."
          example: "IDP"
          enum:
            - "IDP"
            - "APPLICATION"
            - "CONNECTOR"
            - "AUTHENTICATOR"
        properties:
          type: object
          maxProperties: 50
          additionalProperties:
            type: string
            maxLength: 2048
          description: "Generic properties for resource debugging as key-value pairs. Maximum 50 properties allowed. Each property value can be up to 2048 characters. For IDP resource type, the connectionId property is required."
          example:
            "connectionId": "123e4567-e89b-12d3-a456-426614174000"
            "authenticatorName": "OpenIDConnectAuthenticator"

    DebugConnectionResponse:
      type: object
      description: "Debug connection response containing generic debug information and resource-specific metadata."
      properties:
        debugId:
          type: string
          description: "Debug session ID."
          example: "debug-496f5a3f-0094-42f2-8188-d2baa9a1287c"
        status:
          type: string
          description: "Status of the debug operation."
          enum: ["SUCCESS", "IN_PROGRESS", "FAILURE", "DIRECT_RESULT"]
          example: "SUCCESS"
        message:
          type: string
          description: "Generic response message."
          example: "Debug session initiated successfully"
        timestamp:
          type: integer
          format: int64
          description: "Timestamp when the debug operation was processed (in milliseconds)."
          example: 1771217107937
        metadata:
          type: object
          description: "Resource-specific metadata. For IDP OAuth debugging, includes 'authorizationUrl'."
          properties:
            authorizationUrl:
              type: string
              description: "OAuth 2.0 authorization URL for IDP debugging."
              example: "https://api.asgardeo.io/t/linuka/oauth2/authorize?response_type=code&client_id=lfrTEyDGHBEUbeBKoiaosz1y8Aca&redirect_uri=https%3A%2F%2Flocalhost%3A9443%2Fcommonauth"

    # -----------------------------
    # GET /debug/result/{session-id}
    # -----------------------------
    DebugResponse:
      type: object
      properties:
        sessionId:
          type: string
          description: "Debug session identifier."
          example: "debug-session-12345"
        status:
          type: string
          description: "Debug operation status."
          enum: ["SUCCESS", "FAILURE", "IN_PROGRESS"]
        targetIdp:
          type: string
          description: "Target Identity Provider that was tested."
          example: "Google"
        authenticatorUsed:
          type: string
          description: "Authenticator that was used."
          example: "GoogleOIDCAuthenticator"
        authenticationResult:
          $ref: "#/components/schemas/AuthenticationResult"
        claimsAnalysis:
          $ref: "#/components/schemas/ClaimsAnalysis"
        flowEvents:
          type: array
          items:
            $ref: "#/components/schemas/FlowEvent"
          description: "Authentication flow events captured by event listeners."
        errors:
          type: array
          items:
            $ref: "#/components/schemas/DebugError"
        metadata:
          type: object
          additionalProperties:
            type: string
          description: "Additional debug metadata."
    
    AuthenticationResult:
      type: "object"
      properties:
        isAuthenticated:
          type: "boolean"
          description: "Indicates if the user authentication was successful."
        username:
          type: "string"
          description: "The username of the authenticated user."
          example: "alex@wso2.com"
        subjectId:
          type: "string"
          description: "The unique subject identifier."
          example: "a123-b456-c789"
        mappedAttributes:
          type: "object"
          additionalProperties:
            type: "string"
          description: "Key-value pairs of locally mapped user attributes."
          example:
            "http://wso2.org/claims/emailaddress": "alex@wso2.com"

    ClaimsAnalysis:
      type: "object"
      properties:
        idpClaims:
          type: "object"
          additionalProperties:
            type: "string"
          description: "Claims received from the Identity Provider."
          example:
            "sub": "a123-b456-c789"
            "email": "alex@wso2.com"
        mappedLocalClaims:
          type: "object"
          additionalProperties:
            type: "string"
          description: "Claims successfully mapped to local dialect."
          example:
            "http://wso2.org/claims/emailaddress": "alex@wso2.com"
        missingMandatoryClaims:
          type: "array"
          items:
            type: "string"
          description: "A list of mandatory local claims that were not found."
          example:
            - "http://wso2.org/claims/role"

    FlowEvent:
      type: "object"
      properties:
        timestamp:
          type: "string"
          description: "Timestamp of the event."
          example: "2025-10-21T10:30:01Z"
        type:
          type: "string"
          description: "Type of the flow event."
          example: "TOKEN_EXCHANGE"
        details:
          type: "object"
          additionalProperties:
            type: "string"
          description: "Key-value details of the event."
          example:
            endpoint: "https://idp.example.com/oauth2/token"
            status: "200"

    DebugError:
      type: "object"
      properties:
        timestamp:
          type: "string"
          description: "Timestamp when the error occurred."
          example: "2025-10-21T10:30:02Z"
        code:
          type: "string"
          description: "Error code."
          example: "TOKEN_EXCHANGE_FAILURE"
        message:
          type: "string"
          description: "A short error message."
          example: "Failed to exchange token"
        details:
          type: "object"
          additionalProperties:
            type: "string"
          description: "Key-value details of the error."
          example:
            "http_status": "500"
            "response_body": "invalid_grant"
